name: PHP Linter

on:
    push: null

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.1
                    coverage: none

            -   run: composer global require php-parallel-lint/php-parallel-lint

            -   run: /home/runner/.composer/vendor/bin/parallel-lint src tests
